"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import {
  Play,
  Pause,
  SkipBack,
  SkipForward,
  RotateCcw,
  Table2,
  Loader2,
} from "lucide-react";
import { getRuntime, type TraceStep } from "@/lib/python/runtime";
import { explainError } from "@/lib/python/errors";
import { PyEditor } from "@/components/python/PyEditor";
import { ErrorPanel } from "@/components/python/ErrorPanel";
import { useProgress } from "@/lib/store/progress";
import { cn } from "@/lib/utils";

/* ============================================================================
 * Step-through tracer: the hand-trace table, generated by running the code.
 *
 * "Uses hand traces to verify the solutions" is an explicit learning outcome,
 * and the exam asks students to produce trace tables on paper. This runs the
 * real program one line at a time so a student can check the table they drew,
 * or watch how a construct behaves before drawing one.
 * ==========================================================================*/

type Mode = "steps" | "table";

export function StepThrough({
  code: initialCode,
  caption,
  stdin,
  editable = true,
  className,
}: {
  code: string;
  caption?: string;
  stdin?: string[];
  editable?: boolean;
  className?: string;
}) {
  const [code, setCode] = useState(initialCode);
  const [steps, setSteps] = useState<TraceStep[]>([]);
  const [stdout, setStdout] = useState("");
  const [error, setError] = useState<ReturnType<typeof explainError> | null>(null);
  const [index, setIndex] = useState(0);
  const [loading, setLoading] = useState(false);
  const [playing, setPlaying] = useState(false);
  const [mode, setMode] = useState<Mode>("steps");
  const [traced, setTraced] = useState(false);
  const recordTrace = useProgress((s) => s.recordTrace);
  const timer = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => setCode(initialCode), [initialCode]);

  const runTrace = async () => {
    setLoading(true);
    setPlaying(false);
    setError(null);
    const res = await getRuntime().trace(code, { stdin, maxSteps: 2000 });
    setSteps(res.steps ?? []);
    setStdout(res.stdout ?? "");
    setIndex(0);
    setLoading(false);
    if (res.error) setError(explainError(res.error));
    if (!traced) {
      setTraced(true);
      recordTrace();
    }
  };

  // Auto-play walks forward and stops at the end.
  useEffect(() => {
    if (!playing) {
      if (timer.current) clearInterval(timer.current);
      return;
    }
    timer.current = setInterval(() => {
      setIndex((i) => {
        if (i >= steps.length - 1) {
          setPlaying(false);
          return i;
        }
        return i + 1;
      });
    }, 650);
    return () => {
      if (timer.current) clearInterval(timer.current);
    };
  }, [playing, steps.length]);

  const current = steps[index];
  const hasRun = steps.length > 0;

  /** Every variable that ever appears, in first-seen order: the table columns. */
  const columns = useMemo(() => {
    const seen: string[] = [];
    steps.forEach((s) =>
      Object.keys(s.locals).forEach((k) => {
        if (!seen.includes(k)) seen.push(k);
      }),
    );
    return seen;
  }, [steps]);

  /** Output produced up to and including the current step. */
  const outputSoFar = current ? stdout.slice(0, current.out) : "";

  const changedKeys = useMemo(() => {
    if (!current || index === 0) return new Set(Object.keys(current?.locals ?? {}));
    const prev = steps[index - 1];
    const changed = new Set<string>();
    Object.entries(current.locals).forEach(([k, v]) => {
      if (!prev.locals[k] || prev.locals[k].repr !== v.repr) changed.add(k);
    });
    return changed;
  }, [current, index, steps]);

  return (
    <div className={cn("my-5 overflow-hidden rounded-xl border border-line bg-surface", className)}>
      <header className="flex items-center gap-2 border-b border-line bg-sunken px-3.5 py-2.5">
        <Table2 className="size-4 shrink-0 text-[var(--brand)]" />
        <div className="min-w-0 flex-1">
          <p className="text-[13px] font-semibold">Step through it</p>
          {caption && <p className="truncate text-[11.5px] text-subtle">{caption}</p>}
        </div>
        {hasRun && (
          <div className="hidden gap-1 rounded-lg bg-surface p-0.5 sm:flex">
            {(["steps", "table"] as Mode[]).map((m) => (
              <button
                key={m}
                onClick={() => setMode(m)}
                className={cn(
                  "rounded-md px-2 py-1 text-[11.5px] font-medium capitalize transition-colors",
                  mode === m ? "bg-brand-soft text-brand-soft-fg" : "text-subtle hover:text-muted",
                )}
              >
                {m === "steps" ? "Variables" : "Trace table"}
              </button>
            ))}
          </div>
        )}
      </header>

      <PyEditor
        value={code}
        onChange={editable ? setCode : undefined}
        readOnly={!editable}
        activeLine={current?.line ?? null}
        minHeight="70px"
        maxHeight="260px"
        className="rounded-none border-0 border-b"
      />

      <div className="flex flex-wrap items-center gap-1.5 px-3 py-2">
        <button
          onClick={runTrace}
          disabled={loading}
          className="inline-flex h-8 items-center gap-1.5 rounded-lg bg-[var(--brand)] px-3 text-[13px] font-medium text-[var(--brand-fg)] disabled:opacity-50"
        >
          {loading ? <Loader2 className="size-3.5 animate-spin" /> : <RotateCcw className="size-3.5" />}
          {hasRun ? "Re-trace" : "Start tracing"}
        </button>

        {hasRun && (
          <>
            <div className="mx-1 h-5 w-px bg-[var(--border)]" />
            <button
              onClick={() => {
                setPlaying(false);
                setIndex((i) => Math.max(0, i - 1));
              }}
              disabled={index === 0}
              aria-label="Previous step"
              className="rounded-lg p-1.5 text-muted transition-colors hover:bg-hover disabled:opacity-30"
            >
              <SkipBack className="size-4" />
            </button>
            <button
              onClick={() => setPlaying((p) => !p)}
              aria-label={playing ? "Pause" : "Play"}
              className="rounded-lg bg-sunken p-1.5 text-ink transition-colors hover:bg-hover"
            >
              {playing ? <Pause className="size-4" /> : <Play className="size-4" />}
            </button>
            <button
              onClick={() => {
                setPlaying(false);
                setIndex((i) => Math.min(steps.length - 1, i + 1));
              }}
              disabled={index >= steps.length - 1}
              aria-label="Next step"
              className="rounded-lg p-1.5 text-muted transition-colors hover:bg-hover disabled:opacity-30"
            >
              <SkipForward className="size-4" />
            </button>

            <span className="ml-1 font-[family-name:var(--font-mono)] text-[11.5px] tabular-nums text-subtle">
              step {index + 1}/{steps.length} · line {current?.line}
            </span>
          </>
        )}
      </div>

      {hasRun && (
        <div className="px-3 pb-1">
          <input
            type="range"
            min={0}
            max={steps.length - 1}
            value={index}
            onChange={(e) => {
              setPlaying(false);
              setIndex(Number(e.target.value));
            }}
            aria-label="Scrub through the trace"
            className="h-1.5 w-full cursor-pointer appearance-none rounded-pill bg-sunken accent-[var(--brand)]"
          />
        </div>
      )}

      {hasRun && mode === "steps" && (
        <div className="grid gap-3 p-3 sm:grid-cols-2">
          <div>
            <p className="mb-1.5 text-[11px] font-semibold uppercase tracking-wide text-subtle">
              Variables {current?.func !== "main" && `· inside ${current?.func}()`}
            </p>
            <div className="min-h-24 rounded-lg border border-line bg-sunken p-2">
              {Object.keys(current?.locals ?? {}).length === 0 ? (
                <p className="px-1 py-2 text-[12.5px] text-subtle">
                  No variables have been created yet
                </p>
              ) : (
                <ul className="space-y-1">
                  <AnimatePresence initial={false}>
                    {Object.entries(current!.locals).map(([name, v]) => (
                      <motion.li
                        key={name}
                        layout
                        initial={{ opacity: 0, x: -6 }}
                        animate={{ opacity: 1, x: 0 }}
                        exit={{ opacity: 0 }}
                        className={cn(
                          "flex items-center gap-2 rounded-md px-2 py-1.5 transition-colors",
                          changedKeys.has(name) ? "bg-accent-soft" : "bg-surface",
                        )}
                      >
                        <span className="font-[family-name:var(--font-mono)] text-[12.5px] font-semibold text-[var(--brand)]">
                          {name}
                        </span>
                        <span className="text-subtle">=</span>
                        <span className="min-w-0 flex-1 truncate font-[family-name:var(--font-mono)] text-[12.5px]">
                          {v.repr}
                        </span>
                        <span className="shrink-0 rounded bg-sunken px-1.5 py-0.5 text-[10px] font-medium text-subtle">
                          {v.type}
                        </span>
                      </motion.li>
                    ))}
                  </AnimatePresence>
                </ul>
              )}
            </div>
          </div>

          <div>
            <p className="mb-1.5 text-[11px] font-semibold uppercase tracking-wide text-subtle">
              Output so far
            </p>
            <pre className="scrollbar-slim min-h-24 overflow-auto rounded-lg bg-[var(--bg-code)] px-3 py-2 font-[family-name:var(--font-mono)] text-[12.5px] leading-relaxed text-[#d7dbf0]">
              {outputSoFar || <span className="text-[#6b7194]">(nothing printed yet)</span>}
            </pre>
          </div>
        </div>
      )}

      {hasRun && mode === "table" && (
        <div className="scrollbar-slim overflow-x-auto p-3">
          <table className="w-full min-w-max border-collapse text-[12.5px]">
            <thead>
              <tr className="border-b border-line-strong">
                <th className="px-2 py-1.5 text-left font-semibold text-subtle">Step</th>
                <th className="px-2 py-1.5 text-left font-semibold text-subtle">Line</th>
                {columns.map((c) => (
                  <th
                    key={c}
                    className="px-2 py-1.5 text-left font-[family-name:var(--font-mono)] font-semibold text-[var(--brand)]"
                  >
                    {c}
                  </th>
                ))}
                <th className="px-2 py-1.5 text-left font-semibold text-subtle">Output</th>
              </tr>
            </thead>
            <tbody>
              {steps.map((s, i) => (
                <tr
                  key={i}
                  onClick={() => {
                    setPlaying(false);
                    setIndex(i);
                  }}
                  className={cn(
                    "cursor-pointer border-b border-line transition-colors",
                    i === index ? "bg-accent-soft" : "hover:bg-hover",
                  )}
                >
                  <td className="px-2 py-1 tabular-nums text-subtle">{i + 1}</td>
                  <td className="px-2 py-1 tabular-nums">{s.line}</td>
                  {columns.map((c) => (
                    <td key={c} className="px-2 py-1 font-[family-name:var(--font-mono)]">
                      {s.locals[c]?.repr ?? <span className="text-subtle">-</span>}
                    </td>
                  ))}
                  <td className="px-2 py-1 font-[family-name:var(--font-mono)] text-[11.5px] text-subtle">
                    {JSON.stringify(stdout.slice(0, s.out)).slice(1, -1).slice(-24) || "-"}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {error && (
        <div className="px-3 pb-3">
          <ErrorPanel error={error} />
        </div>
      )}
    </div>
  );
}
